export const topics = [
    {id:1,topic:"Censorship in Movies & Our Culture "},
    {id:2,topic:"Do Women make Good Managers? "},
    {id:3,topic:"Advantages of Co-education "},
    {id:4,topic:"Is God Male? "},
    {id:5,topic:"Are Cricketers to be blamed for Match Fixing? "},
    {id:6,topic:"Terrorism in India "},
    {id:7,topic:"How to Deal with High Oil Prices? "},
    {id:8,topic:"Security Cameras & Privacy "},
    {id:9,topic:"Examinations - has it killed education "},
    {id:10,topic:"Classical Music Heritage and the Growing Pop-Culture"},
    {id:11,topic:"Rules are Meant to be Broken "},
    {id:12,topic:"T20 Cricket killing Real Cricketing Skills? "},
    {id:13,topic:"Retirement Age for Politicians "},
    {id:14,topic:"Our Culture is Decaying "},
    {id:15,topic:"Are Indians Less Quality Conscious? "},
    {id:16,topic:"Foreign Universities in India "},
    {id:17,topic:"Films are corrupting the Indian Youth "},
    {id:18,topic:"Is Reservation in Higher Education Only Alternative for Social Equality? "},
    {id:19,topic:"Women are better at Multi-Tasking "},
    {id:20,topic:"Is India a Soft Nation? "},
    {id:21,topic:"Should Smoking be banned completely? "},
    {id:22,topic:"Men are from Mars; Women are from Venus "},
    {id:23,topic:"Is our Political System Reason for our Backwardness? "},
    {id:24,topic:"Marriage is a social trap"},
    {id:25,topic:"Cleanliness is a Fundamental Responsibility of an Indian Citizen "},
    {id:26,topic:"Universal Disarmament is a Must "},
    {id:27,topic:"Should Agricultural Subsidies be stopped? "},
    {id:28,topic:"Effects of Television on Youth "},
    {id:29,topic:"Just as we have smoke free zones, we should have child free zones"},
    {id:30,topic:"Should India break Diplomatic Ties with Pakistan?"},
    {id:31,topic:"Reservations in the Private Sector "},
    {id:32,topic:"Does Morality have an Essence in Corporate Life? "},
    {id:33,topic:"Role of Ethics in Business "},
    {id:34,topic:"Love Marriages Vs Arranged Marriages "},
    {id:35,topic:"Advertising is a Waste of Resources "},
    {id:36,topic:"E-Learning: A Substitute for Classroom Learning? "},
    {id:37,topic:"Nuclear War cannot be won and should not be fought "},
    {id:38,topic:"Whether Hard-Working or Smart-Working is Desirable? "},
    {id:39,topic:"Is Remixing Good Trend in Music? "},
    {id:40,topic:"Should the Government Set-up More IITs and IIMs, OR should it be use the Money for Primary & Secondary Education? "},
    {id:41,topic:"Doctors' Accountability to Improve Health-Care "},
    {id:42,topic:"Educational qualification for Politicians "},
    {id:43,topic:"Indians Perform Better as Individuals than in Groups/Teams "},
    {id:44,topic:"Is the Consumer really the King in India? "},
    {id:45,topic:"Women are not fit for Defense Services "},
    {id:46,topic:"Need for Good Leaders in India "},
    {id:47,topic:"We Need More Entrepreneurs than Managers "},
    {id:48,topic:"Is Love Precious or Poisonous? "},
    {id:49,topic:"Nice Guys Finish Last "},
    {id:50,topic:"Skilled Manpower Shortage in India "},
    {id:51,topic:"Showing Violence and Crimes should not be allowed in films and on television."},
    {id:52,topic:"Should Research on Human Cloning be banned? "},
    {id:53,topic:"If I was the Finance Minister/Prime Minister "},
    {id:54,topic:"Indian villages - our strength or our weakness? "},
    {id:55,topic:"We are not serious about saving Wildlife/Environment "},
    {id:56,topic:"Are beauty contests degrading womanhood? "},
    {id:57,topic:"Religion should not be mixed with Politics"},
    {id:58,topic:"Corruption is a Necessary Evil for Success in Any Sphere "},
    {id:59,topic:"Who says MNCs are superior to Indian companies? "},
    {id:60,topic:"Smaller businesses and start-ups have more scope for professional growth. "},
    {id:61,topic:"Private Educational Institutions: Good or Bad "},
    {id:62,topic:"How can a Business get rid of the Bad Name that it has earned?"},
    {id:63,topic:"Indian Army as a Career Option "},
    {id:64,topic:"Bride burning and dowry may look bad, but are an integral part of India. "},
    {id:65,topic:"India should go for the presidential form of democracy"},
    {id:66,topic:"Influence of Online Social Networks on our Youth "},
    {id:67,topic:"Should Animals be used for Testing New Drugs & Medical Procedures? "},
    {id:68,topic:"Space Missions are a Wastage of Resources for a Resource-Starved Nation like India"},
    {id:69,topic:"Is Dependence on Computers a Good Thing?"},
    {id:70,topic:"Advertisements Cheat People, Hence Should Be Banned "},

];